<!-- CORINE -> VBS4 land cover map -->

<!-- #48 Nodata/Default value -->
<!-- Use bare earth here> -->
<!ENTITY defaultLC "#000000">

<!-- #1 Continuous urban fabric -->
<!ENTITY corineLC1 "#262626">
<!-- #2 Discontinuous urban fabric -->
<!ENTITY corineLC2 "#262626">
<!-- #3 Industrial or commercial units or public facilities -->
<!ENTITY corineLC3 "#262626">
<!-- #4 Road and rail networks and associated land -->
<!-- Map to asphalt in VBS4 -->
<!ENTITY corineLC4 "#343434">
<!-- #5 Port areas -->
<!-- Map to asphalt -->
<!ENTITY corineLC5 "#343434">
<!-- #6 Airports -->
<!-- Map to urban grass when runways are modeled separately -->
<!ENTITY corineLC6 "#0d0d0d">
<!-- #6a Airport runways, taxiways etc. -->
<!-- (in standard CORINE, this will not be differentiated from Airports/corineLC6) -->
<!ENTITY corineLC6a "#343434">
<!-- #7 Mineral extraction site -->
<!ENTITY corineLC7 "#101010">
<!-- #8 Dump sites -->
<!ENTITY corineLC8 "#101010">
<!-- #9 Construction sites -->
<!ENTITY corineLC9 "#282828">
<!-- #10 Green urban areas -->
<!ENTITY corineLC10 "#0d0d0d">
<!-- #11 Recreational areas -->
<!ENTITY corineLC11 "#2d2d2d">
<!-- #12 Non-irrigated arable land -->
<!ENTITY corineLC12 "#121212">
<!-- #13 - Permanently irrigated land -->
<!ENTITY corineLC13 "#171717">
<!-- #14 - Rice fields -->
<!ENTITY corineLC14 "#121212">
<!-- #15 - Vineyards -->
<!ENTITY corineLC15 "#060606">
<!-- #16 - Fruit trees and berry plantations -->
<!ENTITY corineLC16 "#040404">
<!-- #17 - Olive groves -->
<!ENTITY corineLC17 "#020202">
<!-- #18 - Pastures -->
<!ENTITY corineLC18 "#121212">
<!-- #19 - Annual crops associated with permanent crops (currently unused) -->
<!ENTITY corineLC19 "#131313">
<!-- #20 - Complex cultivation patterns -->
<!ENTITY corineLC20 "#040404">
<!-- #21 - Land principally occupied by agriculture with significant areas of natural vegetation (currently unused) -->
<!ENTITY corineLC21 "#060606">
<!-- #22 - Agro-forestry areas (unused) -->
<!ENTITY corineLC22 "#040404">
<!-- #23 Broad-leaved forest -->
<!ENTITY corineLC23 "#040404">
<!-- #24 Coniferous forest  -->
<!ENTITY corineLC24 "#010101">
<!-- #25 Mixed forest  -->
<!ENTITY corineLC25 "#050505">
<!-- #26 Natural grasslands -->
<!ENTITY corineLC26 "#0d0d0d">
<!-- #27 Moors and heathland -->
<!ENTITY corineLC27 "#0e0e0e">
<!-- #28 Sclerophyllous vegetation -->
<!ENTITY corineLC28 "#090909">
<!-- #30 Beaches, dunes, sands -->
<!ENTITY corineLC30 "#252525">
<!-- #31 Bare rocks -->
<!ENTITY corineLC31 "#0f0f0f">
<!-- #32 Sparsely vegetated areas -->
<!ENTITY corineLC32 "#101010">
<!-- #33 Burnt areas (unused) -->
<!ENTITY corineLC33 "#000000">
<!-- #34 Glaciers and perpetual snow -->
<!ENTITY corineLC34 "#0f0f0f">
<!-- #35 Inland marshes -->
<!ENTITY corineLC35 "#111111">
<!-- #36 Peat bogs -->
<!ENTITY corineLC36 "#111111">
<!-- #37 Salt marshes -->
<!ENTITY corineLC37 "#111111">
<!-- #38 Salines -->
<!ENTITY corineLC38 "#111111">
<!-- #39 Intertidal flats -->
<!ENTITY corineLC39 "#111111">
<!-- #40 Water courses -->
<!ENTITY corineLC40 "#000000">
<!-- #41 Water bodies -->
<!ENTITY corineLC41 "#000000">
<!-- #42 Coastal lagoons -->
<!ENTITY corineLC42 "#000000">
<!-- #43  Estuaries (unused) -->
<!ENTITY corineLC43 "#000000">
<!-- #44 Sea and ocean (must be rendered separately due to incomplete coastlines) -->
<!ENTITY corineLC44 "#000000">