<!-- CORINE land cover encodings -->

<!-- #48 Nodata/Default value -->
<!-- Corine defines this - <!ENTITY defaultLC "#ffffff"> -->
<!ENTITY defaultLC "#ffffff">

<!-- #1 Continuous urban fabric -->
<!ENTITY corineLC1 "#e6004d">
<!-- #2 Discontinuous urban fabric -->
<!ENTITY corineLC2 "#ff0000">
<!-- #3 Industrial or commercial units or public facilities -->
<!ENTITY corineLC3 "#cc4df2">
<!-- #4 Road and rail networks and associated land -->
<!ENTITY corineLC4 "#cc0000">
<!-- #5 Port areas -->
<!ENTITY corineLC5 "#e6cccc">
<!-- #6 Airports -->
<!ENTITY corineLC6 "#e6cce6">
<!-- #6a Airport runways, taxiways etc. -->
<!-- (in standard CORINE, this will not be differentiated from Airports/corineLC6) -->
<!ENTITY corineLC6a "#dcc2dc">
<!-- #7 Mineral extraction site -->
<!ENTITY corineLC7 "#a600cc">
<!-- #8 Dump sites -->
<!ENTITY corineLC8 "#a64d00">
<!-- #9 Construction sites -->
<!ENTITY corineLC9 "#ff4dff">
<!-- #10 Green urban areas -->
<!ENTITY corineLC10 "#ffa6ff">
<!-- #11 Recreational areas -->
<!ENTITY corineLC11 "#ffe6ff">
<!-- #12 Non-irrigated arable land -->
<!ENTITY corineLC12 "#ffffa8">
<!-- #13 - Permanently irrigated land -->
<!ENTITY corineLC13 "#ffff00">
<!-- #14 - Rice fields -->
<!ENTITY corineLC14 "#e6e600">
<!-- #15 - Vineyards -->
<!ENTITY corineLC15 "#e68000">
<!-- #16 - Fruit trees and berry plantations -->
<!ENTITY corineLC16 "#e68000">
<!-- #17 - Olive groves -->
<!ENTITY corineLC17 "#e6a600">
<!-- #18 - Pastures -->
<!ENTITY corineLC18 "#e6e64d">
<!-- #19 - Annual crops associated with permanent crops (currently unused) -->
<!ENTITY corineLC19 "#ffe6a6">
<!-- #20 - Complex cultivation patterns -->
<!ENTITY corineLC20 "#ffe64d">
<!-- #21 - Land principally occupied by agriculture with significant areas of natural vegetation (currently unused) -->
<!ENTITY corineLC21 "#e6cc4d">
<!-- #22 - Agro-forestry areas (unused) -->
<!ENTITY corineLC22 "#f2cca6">
<!-- #23 Broad-leaved forest -->
<!ENTITY corineLC23 "#80ff00">
<!-- #24 Coniferous forest  -->
<!ENTITY corineLC24 "#00a600">
<!-- #25 Mixed forest  -->
<!ENTITY corineLC25 "#4dff00">
<!-- #26 Natural grasslands -->
<!ENTITY corineLC26 "#ccf24d">
<!-- #27 Moors and heathland -->
<!ENTITY corineLC27 "#a6ff80">
<!-- #28 Sclerophyllous vegetation -->
<!ENTITY corineLC28 "#a6e64d">
<!-- #30 Beaches, dunes, sands -->
<!ENTITY corineLC30 "#e6e6e6">
<!-- #31 Bare rocks -->
<!ENTITY corineLC31 "#cccccc">
<!-- #32 Sparsely vegetated areas -->
<!ENTITY corineLC32 "#ccffcc">
<!-- #33 Burnt areas (unused) -->
<!ENTITY corineLC33 "#000000">
<!-- #34 Glaciers and perpetual snow -->
<!ENTITY corineLC34 "#a6e6cc">
<!-- #35 Inland marshes -->
<!ENTITY corineLC35 "#a6a6ff">
<!-- #36 Peat bogs -->
<!ENTITY corineLC36 "#4d4dff">
<!-- #37 Salt marshes -->
<!ENTITY corineLC37 "#ccccff">
<!-- #38 Salines -->
<!ENTITY corineLC38 "#e6e6ff">
<!-- #39 Intertidal flats -->
<!ENTITY corineLC39 "#a6a6e6">
<!-- #40 Water courses -->
<!ENTITY corineLC40 "#00ccf2">
<!-- #41 Water bodies -->
<!ENTITY corineLC41 "#80f2e6">
<!-- #42 Coastal lagoons -->
<!ENTITY corineLC42 "#00ffa6">
<!-- #43  Estuaries (unused) -->
<!ENTITY corineLC43 "#a6ffe6">
<!-- #44 Sea and ocean -->
<!ENTITY corineLC44 "#e6f2ff">